### ISSUE TITLE
點選「僅含已繪字符」無法呼叫姐妹字

### ISSUE THREAD

**Issue by garyyau927** [3type/EOD#4]
您好！

我在使用 EOD 時，發現如果點選了「僅含已繪字符」就無法呼叫姐妹字，出現以下錯誤。若果沒有點選「僅含已繪字符」，則能呼叫姐妹字。請問該如何解決？感謝！

<img width="748" alt="Screenshot 2023-03-22 at 8 22 33 PM" src="https://user-images.githubusercontent.com/31500821/226903705-15411419-7617-4f01-9923-06dc08fac6b0.png">

Best,
Gary

**Comment by mumchristmas** [comment]
抱歉之前一直没留意到这条commit。
筛选基于glyph的tag数据，可能在插件写入后，又有其他工具、操作修改了原先工程文件中的tag数据。
已在v2.4.6(#8a269ff)中加入额外检查步骤，避免error。
