### ISSUE TITLE
IDS 数据打包

### ISSUE THREAD

**Issue by yshumy** [3type/EOD#5]
You can hack the following code to add your own sets:
- `datatool-uniSet.py`: package the character set into python pickle object, then save to `.pdata` file with gzip.

如果能把这个制作步骤讲详细一点就好了。

**Comment by mumchristmas** [comment]
直接阅读代码即可，ids源文件和自己的补丁覆盖集都会依次读入，然后运行py会直接打包为pdata文件。
再到插件文件夹中找到并替换原始pdata。

**Comment by yshumy** [comment]
> 直接阅读代码即可，ids源文件和自己的补丁覆盖集都会依次读入，然后运行py会直接打包为pdata文件。 再到插件文件夹中找到并替换原始pdata。

现在有没有可能利用IDS数据，引入人工智能识别，实现自动拆分任意汉字部件并在Glyphs中自动关联智能部件？
